export { default as HomePage } from "./HomePage";
export { default as SearchPage } from "./SearchPage";
export { default as ErrorPage } from "./ErrorPage";
export { default as DetailPage } from "./DetailPage";
export { default as BookingPage } from "./BookingPage";
export { default as ConfirmationPage } from "./ConfirmationPage";
export { default as ForgotPasswordPage } from "./ForgotPasswordPage";
export { default as BookingStatusPage } from "./BookingStatusPage";
export { default as ListBookingPage } from "./ListBookingPage";
