export const cities = [
  "TP HCM",
  "Nha Trang",
  "Hoi An",
  "Da Lat",
  "Ha Noi",
  "Hai Phong",
  "Da Nang",
  "Can Tho",
  "Thai Nguyen",
  "Quang Ninh",
  "Vinh Phuc",
  "Bac Ninh",
  "Hai Duong",
  "Thanh Hoa",
  "Ninh Binh",
  "Quang Nam",
  "Khanh Hoa",
  "Lam Dong",
  "Binh Duong",
  "Dong Nai",
  "Ba Ria - Vung Tau",
  "Dong Thap",
  "An Giang",
  "Kien Giang",
  "Hau Giang",
  "Ca Mau",
];
